name: mobile_app
description: "ReliefNet AI mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.6.0
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0
  provider: ^6.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
